# Generated by Django 3.0.7 on 2020-06-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=64)),
                ('entry_time', models.TimeField(auto_now_add=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
