# Generated by Django 3.0.7 on 2020-07-08 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=64)),
                ('accountBalance', models.CharField(max_length=64)),
                ('accountType', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='dbAccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountType', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='dbCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='dbEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=64, null=True)),
                ('entryTime', models.TimeField(default=django.utils.timezone.now, null=True)),
                ('entryDate', models.DateField(default=django.utils.timezone.now, null=True)),
                ('fromAccount', models.CharField(max_length=64, null=True)),
                ('toAccount', models.CharField(max_length=64, null=True)),
                ('entryNote', models.CharField(max_length=64, null=True)),
                ('type', models.CharField(max_length=64)),
            ],
        ),
    ]
