# Generated by Django 3.0.7 on 2020-06-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateTimeField(verbose_name='auto_now_add=True'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_time',
            field=models.TimeField(verbose_name='auto_now_add=True'),
        ),
    ]
