# Generated by Django 3.0.7 on 2020-08-11 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbcategory',
            old_name='category',
            new_name='categoryName',
        ),
        migrations.AddField(
            model_name='dbcategory',
            name='categoryType',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dbentry',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.dbCategory'),
        ),
        migrations.AlterField(
            model_name='dbentry',
            name='fromAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromAccount', to='walletapp.dbAccount'),
        ),
        migrations.AlterField(
            model_name='dbentry',
            name='toAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toAccount', to='walletapp.dbAccount'),
        ),
    ]
