# Generated by Django 3.0.7 on 2020-08-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0002_auto_20200811_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbaccount',
            name='accountBalance',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dbaccount',
            name='accountName',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dbaccount',
            name='accountType',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
