# Generated by Django 3.0.7 on 2020-06-17 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0002_auto_20200617_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
