# Generated by Django 3.0.7 on 2020-08-11 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0003_auto_20200811_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbaccount',
            name='accountType',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dbentry',
            name='fromAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromAccount', to='walletapp.dbAccount'),
        ),
        migrations.AlterField(
            model_name='dbentry',
            name='toAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toAccount', to='walletapp.dbAccount'),
        ),
    ]
