# Generated by Django 3.0.7 on 2020-06-20 07:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0003_auto_20200617_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=64)),
                ('accountBalance', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='dbAccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountType', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='dbCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='dbEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=64)),
                ('entryTime', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('entryDate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('fromAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromAccount', to='walletapp.dbAccount')),
                ('toAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toAccount', to='walletapp.dbAccount')),
            ],
        ),
        migrations.DeleteModel(
            name='entry',
        ),
        migrations.AddField(
            model_name='dbaccount',
            name='accountType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletapp.dbAccountType'),
        ),
    ]
