# Generated by Django 3.0.7 on 2020-06-20 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0004_auto_20200620_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletapp.dbCategory'),
        ),
    ]
