# Generated by Django 3.0.7 on 2020-08-16 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0004_auto_20200811_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbentry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.dbCategory'),
        ),
    ]
