# Generated by Django 3.0.7 on 2020-06-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0005_auto_20200620_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbaccount',
            name='accountType',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='dbentry',
            name='category',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='dbentry',
            name='fromAccount',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='dbentry',
            name='toAccount',
            field=models.CharField(max_length=64),
        ),
    ]
