# Generated by Django 3.0.7 on 2020-07-05 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0007_auto_20200624_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbentry',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dbentry',
            name='entryDate',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='dbentry',
            name='entryTime',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='dbentry',
            name='fromAccount',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dbentry',
            name='toAccount',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
